---
- name: Install Apache
  hosts: all
  become: true

  handlers:
    - name: restart apache
      service: 
        name: "{{ apache_service }}"
        state: restarted
    
    - name: restart memcached
      service: 
        name: memcached
        state: restarted

  pre_tasks:
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"

  tasks:
   -  name: Add an environment variable to the remote user's shell.
      lineinfile:
          dest: "~/.bash_profile"
          regexp: '^ENV_VAR='
          line: 'ENV_VAR=value'
      become: false
   
   -  name: Get the value of an environment variable.
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      register: foo
      become: false
      args:
        executable: /bin/bash

   -  debug: msg="The variable is {{ foo.stdout }}"

   -  name: Download a file
      get_url:
        url: http://ipv4.download.thinkbroadband.com/20MB.zip
        dest: /tmp

   -  name: Install Apache
      package:
        name:
          - "{{ apache_package }}"
          #- httpd-devel
        state: present

   -  name: Copy test config file.
      copy: 
        src: files/test.conf
        dest: "{{apache_config_dir}}/test.conf"
      notify: 
        - restart apache
        - restart memcached

   -  name: Make sure Apache is started now and at boot.
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
          
