## this is plain text
---
- name: Install Apache
  hosts: all
  become: true

  handlers:
    - name: restart apache
      service: 
        name: httpd
        state: restarted
    
    - name: restart memcached
      service: 
        name: memcached
        state: restarted


  tasks:
   -  name: Add an environment variable to the remote user's shell.
      lineinfile:
          dest: "~/.bash_profile"
          regexp: '^ENV_VAR='
          line: 'ENV_VAR=value'
      become: false
   
   -  name: Get the value of an environment variable.
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      register: foo

   -  debug: msg="The variable is {{ foo.stdout }}"

   -  name: Download a file
      get_url:
        url: http://ipv4.download.thinkbroadband.com/20MB.zip
        dest: /tmp
        
   -  name: Install Apache
      yum:
        name:
          - httpd
          - httpd-devel
        state: present

   -  name: Copy test config file.
      copy: 
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: 
        - restart apache
        - restart memcached

   -  name: Make sure Apache is started now and at boot.
      service:
        name: httpd
        state: started
        enabled: true
          
